<?php

namespace Proxies\__CG__\models\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class InfoDesk extends \models\Entities\InfoDesk implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getID()
    {
        $this->__load();
        return parent::getID();
    }

    public function getSection()
    {
        $this->__load();
        return parent::getSection();
    }

    public function setSection(\models\Entities\InfoSection $value)
    {
        $this->__load();
        return parent::setSection($value);
    }

    public function setName($value)
    {
        $this->__load();
        return parent::setName($value);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setTitle($value)
    {
        $this->__load();
        return parent::setTitle($value);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setContent($value)
    {
        $this->__load();
        return parent::setContent($value);
    }

    public function getContent()
    {
        $this->__load();
        return parent::getContent();
    }

    public function setIcon($value)
    {
        $this->__load();
        return parent::setIcon($value);
    }

    public function getIcon()
    {
        $this->__load();
        return parent::getIcon();
    }

    public function getIconURL()
    {
        $this->__load();
        return parent::getIconURL();
    }

    public function setPosition($value)
    {
        $this->__load();
        return parent::setPosition($value);
    }

    public function getPosition()
    {
        $this->__load();
        return parent::getPosition();
    }

    public function setFeatured($value)
    {
        $this->__load();
        return parent::setFeatured($value);
    }

    public function getFeatured()
    {
        $this->__load();
        return parent::getFeatured();
    }

    public function setStatus($value)
    {
        $this->__load();
        return parent::setStatus($value);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setImage(\models\Entities\Images\PageImage $value)
    {
        $this->__load();
        return parent::setImage($value);
    }

    public function getImages()
    {
        $this->__load();
        return parent::getImages();
    }

    public function getURL()
    {
        $this->__load();
        return parent::getURL();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'title', 'content', 'icon', 'position', 'featured', 'status', 'section');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}