<?php

namespace Proxies\__CG__\models\Entities\Product\Review;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ReviewSpecification extends \models\Entities\Product\Review\ReviewSpecification implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setID($value)
    {
        $this->__load();
        return parent::setID($value);
    }

    public function getID()
    {
        $this->__load();
        return parent::getID();
    }

    public function setName($value)
    {
        $this->__load();
        return parent::setName($value);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setPosition($value)
    {
        $this->__load();
        return parent::setPosition($value);
    }

    public function getPosition()
    {
        $this->__load();
        return parent::getPosition();
    }

    public function setRating(\models\Entities\Product\Review\ReviewRating $value)
    {
        $this->__load();
        return parent::setRating($value);
    }

    public function getRatings()
    {
        $this->__load();
        return parent::getRatings();
    }

    public function setSubcategory(\models\Entities\Product\Subcategory $value)
    {
        $this->__load();
        return parent::setSubcategory($value);
    }

    public function getSubcategory()
    {
        $this->__load();
        return parent::getSubcategory();
    }

    public function initRatings()
    {
        $this->__load();
        return parent::initRatings();
    }

    public function getRatingIdList()
    {
        $this->__load();
        return parent::getRatingIdList();
    }

    public function getDefaultRatingID()
    {
        $this->__load();
        return parent::getDefaultRatingID();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'position', 'subcategory', 'ratings');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}