<?php

namespace Proxies\__CG__\models\Entities\Product;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Master extends \models\Entities\Product\Master implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getID()
    {
        $this->__load();
        return parent::getID();
    }

    public function getMasterID()
    {
        $this->__load();
        return parent::getMasterID();
    }

    public function getCategoryID()
    {
        $this->__load();
        return parent::getCategoryID();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getPriceType()
    {
        $this->__load();
        return parent::getPriceType();
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function getArchive()
    {
        $this->__load();
        return parent::getArchive();
    }

    public function getBrand()
    {
        $this->__load();
        return parent::getBrand();
    }

    public function getStock()
    {
        $this->__load();
        return parent::getStock();
    }

    public function getBrandName()
    {
        $this->__load();
        return parent::getBrandName();
    }

    public function getBrandImage()
    {
        $this->__load();
        return parent::getBrandImage();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'master_id', 'category_id', 'name', 'price_type', 'price', 'description', 'archive', 'stock', 'brand', 'product');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}