<?php

namespace Proxies\__CG__\models\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class LocationData extends \models\Entities\LocationData implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setID($value)
    {
        $this->__load();
        return parent::setID($value);
    }

    public function getID()
    {
        $this->__load();
        return parent::getID();
    }

    public function setAlias($value)
    {
        $this->__load();
        return parent::setAlias($value);
    }

    public function getAlias()
    {
        $this->__load();
        return parent::getAlias();
    }

    public function setEmail($value)
    {
        $this->__load();
        return parent::setEmail($value);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setLatitude($value)
    {
        $this->__load();
        return parent::setLatitude($value);
    }

    public function getLatitude()
    {
        $this->__load();
        return parent::getLatitude();
    }

    public function setLongitude($value)
    {
        $this->__load();
        return parent::setLongitude($value);
    }

    public function getLongitude()
    {
        $this->__load();
        return parent::getLongitude();
    }

    public function setAddress($value)
    {
        $this->__load();
        return parent::setAddress($value);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function setPhones($value)
    {
        $this->__load();
        return parent::setPhones($value);
    }

    public function getPhones()
    {
        $this->__load();
        return parent::getPhones();
    }

    public function setInfo($value)
    {
        $this->__load();
        return parent::setInfo($value);
    }

    public function getInfo()
    {
        $this->__load();
        return parent::getInfo();
    }

    public function setIcon($value)
    {
        $this->__load();
        return parent::setIcon($value);
    }

    public function getIcon()
    {
        $this->__load();
        return parent::getIcon();
    }

    public function setPublic($value)
    {
        $this->__load();
        return parent::setPublic($value);
    }

    public function getPublic()
    {
        $this->__load();
        return parent::getPublic();
    }

    public function getIconURL()
    {
        $this->__load();
        return parent::getIconURL();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'location_id', 'alias', 'email', 'latitude', 'longitude', 'address', 'phones', 'info', 'icon', 'public', 'images');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}