<?php

namespace Proxies\__CG__\models\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Article extends \models\Entities\Article implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getID()
    {
        $this->__load();
        return parent::getID();
    }

    public function setApplianceID($value)
    {
        $this->__load();
        return parent::setApplianceID($value);
    }

    public function getApplianceID()
    {
        $this->__load();
        return parent::getApplianceID();
    }

    public function setCategory($value)
    {
        $this->__load();
        return parent::setCategory($value);
    }

    public function getCategory()
    {
        $this->__load();
        return parent::getCategory();
    }

    public function setDate($value)
    {
        $this->__load();
        return parent::setDate($value);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function getFormatedDate()
    {
        $this->__load();
        return parent::getFormatedDate();
    }

    public function setTitle($value)
    {
        $this->__load();
        return parent::setTitle($value);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setContent($value)
    {
        $this->__load();
        return parent::setContent($value);
    }

    public function getContent()
    {
        $this->__load();
        return parent::getContent();
    }

    public function setThumb($value)
    {
        $this->__load();
        return parent::setThumb($value);
    }

    public function getThumb()
    {
        $this->__load();
        return parent::getThumb();
    }

    public function getThumbURL()
    {
        $this->__load();
        return parent::getThumbURL();
    }

    public function setImage($value)
    {
        $this->__load();
        return parent::setImage($value);
    }

    public function getImage()
    {
        $this->__load();
        return parent::getImage();
    }

    public function getImageURL()
    {
        $this->__load();
        return parent::getImageURL();
    }

    public function setStatus($value)
    {
        $this->__load();
        return parent::setStatus($value);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatisticVisits($value)
    {
        $this->__load();
        return parent::setStatisticVisits($value);
    }

    public function getStatisticVisits()
    {
        $this->__load();
        return parent::getStatisticVisits();
    }

    public function setStatisticVotes($value)
    {
        $this->__load();
        return parent::setStatisticVotes($value);
    }

    public function getStatisticVotes()
    {
        $this->__load();
        return parent::getStatisticVotes();
    }

    public function setStatisticRating($value)
    {
        $this->__load();
        return parent::setStatisticRating($value);
    }

    public function getStatisticRating()
    {
        $this->__load();
        return parent::getStatisticRating();
    }

    public function setStatisticComments($value)
    {
        $this->__load();
        return parent::setStatisticComments($value);
    }

    public function getStatisticComments()
    {
        $this->__load();
        return parent::getStatisticComments();
    }

    public function setContentImage($value)
    {
        $this->__load();
        return parent::setContentImage($value);
    }

    public function getContentImages()
    {
        $this->__load();
        return parent::getContentImages();
    }

    public function setSummary($value)
    {
        $this->__load();
        return parent::setSummary($value);
    }

    public function getSummary()
    {
        $this->__load();
        return parent::getSummary();
    }

    public function setProduct(\models\Entities\Product $value)
    {
        $this->__load();
        return parent::setProduct($value);
    }

    public function getProducts()
    {
        $this->__load();
        return parent::getProducts();
    }

    public function getFrontURL()
    {
        $this->__load();
        return parent::getFrontURL();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'appliance_id', 'date', 'title', 'content', 'thumb', 'image', 'status', 'summary', 'statistic_visits', 'statistic_votes', 'statistic_rating', 'statistic_comments', 'category', 'images', 'products', 'highlights');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}