<?php

namespace Proxies\__CG__\models\Entities\Product;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Data extends \models\Entities\Product\Data implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setProduct($value)
    {
        $this->__load();
        return parent::setProduct($value);
    }

    public function getProduct()
    {
        $this->__load();
        return parent::getProduct();
    }

    public function setProductSticker(\models\Entities\Product\Sticker $value)
    {
        $this->__load();
        return parent::setProductSticker($value);
    }

    public function getProductStickers()
    {
        $this->__load();
        return parent::getProductStickers();
    }

    public function setWarranty($value)
    {
        $this->__load();
        return parent::setWarranty($value);
    }

    public function getWarranty()
    {
        $this->__load();
        return parent::getWarranty();
    }

    public function setName($value)
    {
        $this->__load();
        return parent::setName($value);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setOther($value)
    {
        $this->__load();
        return parent::setOther($value);
    }

    public function getOther()
    {
        $this->__load();
        return parent::getOther();
    }

    public function setPriceList($value)
    {
        $this->__load();
        return parent::setPriceList($value);
    }

    public function getPriceList()
    {
        $this->__load();
        return parent::getPriceList();
    }

    public function setPromotion($value)
    {
        $this->__load();
        return parent::setPromotion($value);
    }

    public function getPromotion()
    {
        $this->__load();
        return parent::getPromotion();
    }

    public function setSale($value)
    {
        $this->__load();
        return parent::setSale($value);
    }

    public function getSale()
    {
        $this->__load();
        return parent::getSale();
    }

    public function setOutlet($value)
    {
        $this->__load();
        return parent::setOutlet($value);
    }

    public function getOutlet()
    {
        $this->__load();
        return parent::getOutlet();
    }

    public function setHighlightCategory($value)
    {
        $this->__load();
        return parent::setHighlightCategory($value);
    }

    public function getHighlightCategory()
    {
        $this->__load();
        return parent::getHighlightCategory();
    }

    public function setHighlightSubcategory($value)
    {
        $this->__load();
        return parent::setHighlightSubcategory($value);
    }

    public function getHighlightSubcategory()
    {
        $this->__load();
        return parent::getHighlightSubcategory();
    }

    public function setStatisticVisits($value)
    {
        $this->__load();
        return parent::setStatisticVisits($value);
    }

    public function getStatisticVisits()
    {
        $this->__load();
        return parent::getStatisticVisits();
    }

    public function setStatisticVotes($value)
    {
        $this->__load();
        return parent::setStatisticVotes($value);
    }

    public function getStatisticVotes()
    {
        $this->__load();
        return parent::getStatisticVotes();
    }

    public function setStatisticRating($value)
    {
        $this->__load();
        return parent::setStatisticRating($value);
    }

    public function getStatisticRating()
    {
        $this->__load();
        return parent::getStatisticRating();
    }

    public function setStatisticSold($value)
    {
        $this->__load();
        return parent::setStatisticSold($value);
    }

    public function getStatisticSold()
    {
        $this->__load();
        return parent::getStatisticSold();
    }

    public function setReleaseDate()
    {
        $this->__load();
        return parent::setReleaseDate();
    }

    public function getReleaseDate()
    {
        $this->__load();
        return parent::getReleaseDate();
    }

    public function getFormatedReleaseDate()
    {
        $this->__load();
        return parent::getFormatedReleaseDate();
    }

    public function setCategory($value)
    {
        $this->__load();
        return parent::setCategory($value);
    }

    public function getCategory()
    {
        $this->__load();
        return parent::getCategory();
    }

    public function setSubcategory($value)
    {
        $this->__load();
        return parent::setSubcategory($value);
    }

    public function getSubcategory()
    {
        $this->__load();
        return parent::getSubcategory();
    }

    public function setStatus($value)
    {
        $this->__load();
        return parent::setStatus($value);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'name', 'description', 'price_list', 'promotion', 'sale', 'outlet', 'highlight_category', 'highlight_subcategory', 'statistic_visits', 'statistic_votes', 'statistic_rating', 'statistic_sold', 'release_date', 'status', 'product', 'stickers', 'category', 'subcategory', 'warranty');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}