<?php

namespace Proxies\__CG__\models\Entities\Questionnaire;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Question extends \models\Entities\Questionnaire\Question implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getID()
    {
        $this->__load();
        return parent::getID();
    }

    public function setType($value)
    {
        $this->__load();
        return parent::setType($value);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setText($value)
    {
        $this->__load();
        return parent::setText($value);
    }

    public function getText()
    {
        $this->__load();
        return parent::getText();
    }

    public function setPosition($value)
    {
        $this->__load();
        return parent::setPosition($value);
    }

    public function getPosition()
    {
        $this->__load();
        return parent::getPosition();
    }

    public function setQuestionnaire(\models\Entities\Questionnaire $value)
    {
        $this->__load();
        return parent::setQuestionnaire($value);
    }

    public function getQuestionnaire()
    {
        $this->__load();
        return parent::getQuestionnaire();
    }

    public function setAnswer(\models\Entities\Questionnaire\Answer $value)
    {
        $this->__load();
        return parent::setAnswer($value);
    }

    public function getAnswers()
    {
        $this->__load();
        return parent::getAnswers();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'type', 'text', 'position', 'questionnaire', 'answers');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}