<?php

namespace Proxies\__CG__\models\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Section extends \models\Entities\Section implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getID()
    {
        $this->__load();
        return parent::getID();
    }

    public function setName($value)
    {
        $this->__load();
        return parent::setName($value);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setController($value)
    {
        $this->__load();
        return parent::setController($value);
    }

    public function getController()
    {
        $this->__load();
        return parent::getController();
    }

    public function setMethod($value)
    {
        $this->__load();
        return parent::setMethod($value);
    }

    public function getMethod()
    {
        $this->__load();
        return parent::getMethod();
    }

    public function getVisibility()
    {
        $this->__load();
        return parent::getVisibility();
    }

    public function getVendorVisibility()
    {
        $this->__load();
        return parent::getVendorVisibility();
    }

    public function getMobileVisibility()
    {
        $this->__load();
        return parent::getMobileVisibility();
    }

    public function getChildren()
    {
        $this->__load();
        return parent::getChildren();
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function getURI()
    {
        $this->__load();
        return parent::getURI();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'controller', 'method', 'visibility', 'vendor_visibility', 'mobile_visibility', 'children', 'parent');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}