<?php

namespace Proxies\__CG__\models\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Product extends \models\Entities\Product implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setID($value)
    {
        $this->__load();
        return parent::setID($value);
    }

    public function getID()
    {
        $this->__load();
        return parent::getID();
    }

    public function setManufacturerID($value)
    {
        $this->__load();
        return parent::setManufacturerID($value);
    }

    public function getManufacturerID()
    {
        $this->__load();
        return parent::getManufacturerID();
    }

    public function setVendorID($value)
    {
        $this->__load();
        return parent::setVendorID($value);
    }

    public function getVendorID()
    {
        $this->__load();
        return parent::getVendorID();
    }

    public function setName($value)
    {
        $this->__load();
        return parent::setName($value);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setDescription($value)
    {
        $this->__load();
        return parent::setDescription($value);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setInformation($value)
    {
        $this->__load();
        return parent::setInformation($value);
    }

    public function getInformation()
    {
        $this->__load();
        return parent::getInformation();
    }

    public function setOther($value)
    {
        $this->__load();
        return parent::setOther($value);
    }

    public function getOther()
    {
        $this->__load();
        return parent::getOther();
    }

    public function setPriceList($value)
    {
        $this->__load();
        return parent::setPriceList($value);
    }

    public function getPriceList()
    {
        $this->__load();
        return parent::getPriceList();
    }

    public function setFeatured($value)
    {
        $this->__load();
        return parent::setFeatured($value);
    }

    public function getFeatured()
    {
        $this->__load();
        return parent::getFeatured();
    }

    public function setPromotion($value)
    {
        $this->__load();
        return parent::setPromotion($value);
    }

    public function getPromotion()
    {
        $this->__load();
        return parent::getPromotion();
    }

    public function setSale($value)
    {
        $this->__load();
        return parent::setSale($value);
    }

    public function getSale()
    {
        $this->__load();
        return parent::getSale();
    }

    public function setOutlet($value)
    {
        $this->__load();
        return parent::setOutlet($value);
    }

    public function getOutlet()
    {
        $this->__load();
        return parent::getOutlet();
    }

    public function setHighlightCategory($value)
    {
        $this->__load();
        return parent::setHighlightCategory($value);
    }

    public function getHighlightCategory()
    {
        $this->__load();
        return parent::getHighlightCategory();
    }

    public function setHighlightSubcategory($value)
    {
        $this->__load();
        return parent::setHighlightSubcategory($value);
    }

    public function getHighlightSubcategory()
    {
        $this->__load();
        return parent::getHighlightSubcategory();
    }

    public function setReleaseDate()
    {
        $this->__load();
        return parent::setReleaseDate();
    }

    public function getReleaseDate()
    {
        $this->__load();
        return parent::getReleaseDate();
    }

    public function getFormatedReleaseDate()
    {
        $this->__load();
        return parent::getFormatedReleaseDate();
    }

    public function setStatus($value)
    {
        $this->__load();
        return parent::setStatus($value);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setWarranty($value)
    {
        $this->__load();
        return parent::setWarranty($value);
    }

    public function getWarranty()
    {
        $this->__load();
        return parent::getWarranty();
    }

    public function setStatisticVisits($value)
    {
        $this->__load();
        return parent::setStatisticVisits($value);
    }

    public function getStatisticVisits()
    {
        $this->__load();
        return parent::getStatisticVisits();
    }

    public function setStatisticVotes($value)
    {
        $this->__load();
        return parent::setStatisticVotes($value);
    }

    public function getStatisticVotes()
    {
        $this->__load();
        return parent::getStatisticVotes();
    }

    public function setStatisticRating($value)
    {
        $this->__load();
        return parent::setStatisticRating($value);
    }

    public function getStatisticRating()
    {
        $this->__load();
        return parent::getStatisticRating();
    }

    public function setStatisticSold($value)
    {
        $this->__load();
        return parent::setStatisticSold($value);
    }

    public function getStatisticSold()
    {
        $this->__load();
        return parent::getStatisticSold();
    }

    public function setStatisticComments($value)
    {
        $this->__load();
        return parent::setStatisticComments($value);
    }

    public function getStatisticComments()
    {
        $this->__load();
        return parent::getStatisticComments();
    }

    public function setPrice($value)
    {
        $this->__load();
        return parent::setPrice($value);
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function setPriceRetail($value)
    {
        $this->__load();
        return parent::setPriceRetail($value);
    }

    public function getPriceRetail()
    {
        $this->__load();
        return parent::getPriceRetail();
    }

    public function setOldPrice($value)
    {
        $this->__load();
        return parent::setOldPrice($value);
    }

    public function getOldPrice()
    {
        $this->__load();
        return parent::getOldPrice();
    }

    public function setBrand($value)
    {
        $this->__load();
        return parent::setBrand($value);
    }

    public function getBrand()
    {
        $this->__load();
        return parent::getBrand();
    }

    public function setCategory($value)
    {
        $this->__load();
        return parent::setCategory($value);
    }

    public function getCategory()
    {
        $this->__load();
        return parent::getCategory();
    }

    public function setSubcategory($value)
    {
        $this->__load();
        return parent::setSubcategory($value);
    }

    public function getSubcategory()
    {
        $this->__load();
        return parent::getSubcategory();
    }

    public function getSubcategoryName()
    {
        $this->__load();
        return parent::getSubcategoryName();
    }

    public function getFilters()
    {
        $this->__load();
        return parent::getFilters();
    }

    public function getProductColors()
    {
        $this->__load();
        return parent::getProductColors();
    }

    public function getProductSizes()
    {
        $this->__load();
        return parent::getProductSizes();
    }

    public function setImage(\models\Entities\Images\ProductImage $value)
    {
        $this->__load();
        return parent::setImage($value);
    }

    public function getImages()
    {
        $this->__load();
        return parent::getImages();
    }

    public function setVideo(\models\Entities\Product\Video $value)
    {
        $this->__load();
        return parent::setVideo($value);
    }

    public function getVideos()
    {
        $this->__load();
        return parent::getVideos();
    }

    public function setBundle(\models\Entities\Product\Bundle $value)
    {
        $this->__load();
        return parent::setBundle($value);
    }

    public function getBundles()
    {
        $this->__load();
        return parent::getBundles();
    }

    public function setSticker($value)
    {
        $this->__load();
        return parent::setSticker($value);
    }

    public function getSticker()
    {
        $this->__load();
        return parent::getSticker();
    }

    public function setStickers($value)
    {
        $this->__load();
        return parent::setStickers($value);
    }

    public function getStickers()
    {
        $this->__load();
        return parent::getStickers();
    }

    public function setProductFilter(\models\Entities\Product\Filter $value)
    {
        $this->__load();
        return parent::setProductFilter($value);
    }

    public function getProductFilters()
    {
        $this->__load();
        return parent::getProductFilters();
    }

    public function setProductTextFilter(\models\Entities\Product\TextFilter $value)
    {
        $this->__load();
        return parent::setProductTextFilter($value);
    }

    public function getProductTextFilters()
    {
        $this->__load();
        return parent::getProductTextFilters();
    }

    public function setCategoryHighlight($value)
    {
        $this->__load();
        return parent::setCategoryHighlight($value);
    }

    public function getCategoryHighlights()
    {
        $this->__load();
        return parent::getCategoryHighlights();
    }

    public function setVat($value)
    {
        $this->__load();
        return parent::setVat($value);
    }

    public function getVat()
    {
        $this->__load();
        return parent::getVat();
    }

    public function setVendor($value)
    {
        $this->__load();
        return parent::setVendor($value);
    }

    public function getVendor()
    {
        $this->__load();
        return parent::getVendor();
    }

    public function getBundle($id)
    {
        $this->__load();
        return parent::getBundle($id);
    }

    public function getTechnologies()
    {
        $this->__load();
        return parent::getTechnologies();
    }

    public function getPriceHistory()
    {
        $this->__load();
        return parent::getPriceHistory();
    }

    public function getPriceHistoryString()
    {
        $this->__load();
        return parent::getPriceHistoryString();
    }

    public function getFormatedPrice()
    {
        $this->__load();
        return parent::getFormatedPrice();
    }

    public function getURL()
    {
        $this->__load();
        return parent::getURL();
    }

    public function getImage($path)
    {
        $this->__load();
        return parent::getImage($path);
    }

    public function getImageName()
    {
        $this->__load();
        return parent::getImageName();
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function countComments()
    {
        $this->__load();
        return parent::countComments();
    }

    public function getFilter($specification)
    {
        $this->__load();
        return parent::getFilter($specification);
    }

    public function getTextFilter($specification)
    {
        $this->__load();
        return parent::getTextFilter($specification);
    }

    public function getBrandName()
    {
        $this->__load();
        return parent::getBrandName();
    }

    public function getBrandImage()
    {
        $this->__load();
        return parent::getBrandImage();
    }

    public function getFilterList()
    {
        $this->__load();
        return parent::getFilterList();
    }

    public function removeBundles($id_list)
    {
        $this->__load();
        return parent::removeBundles($id_list);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'manufacturer_id', 'vendor_id', 'name', 'description', 'information', 'other', 'price_list', 'featured', 'promotion', 'sale', 'outlet', 'highlight_category', 'highlight_subcategory', 'statistic_visits', 'statistic_votes', 'statistic_rating', 'statistic_sold', 'statistic_comments', 'release_date', 'price', 'price_retail', 'old_price', 'status', 'vat', 'vendor', 'brand', 'category', 'subcategory', 'sticker', 'warranty', 'images', 'videos', 'text_filter', 'comments', 'questions', 'filters', 'bundles', 'category_highlights', 'product_colors', 'product_sizes', 'stickers');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}