<?php

namespace Proxies\__CG__\models\Entities\Product;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Bundle extends \models\Entities\Product\Bundle implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getID()
    {
        $this->__load();
        return parent::getID();
    }

    public function setName($value)
    {
        $this->__load();
        return parent::setName($value);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setPrice($value)
    {
        $this->__load();
        return parent::setPrice($value);
    }

    public function setItem(\models\Entities\Product\Bundle\BundleItem $value)
    {
        $this->__load();
        return parent::setItem($value);
    }

    public function getItems()
    {
        $this->__load();
        return parent::getItems();
    }

    public function getTotalItems()
    {
        $this->__load();
        return parent::getTotalItems();
    }

    public function getPrice($format = false)
    {
        $this->__load();
        return parent::getPrice($format);
    }

    public function getSalePrice($product_price, $format = false)
    {
        $this->__load();
        return parent::getSalePrice($product_price, $format);
    }

    public function productExists($id)
    {
        $this->__load();
        return parent::productExists($id);
    }

    public function removeItems()
    {
        $this->__load();
        return parent::removeItems();
    }

    public function getURL()
    {
        $this->__load();
        return parent::getURL();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'price', 'items');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}